"""Remove user_id and users table

Revision ID: f7ba904fb211
Revises: 3c2394a5856e
Create Date: 2025-08-09 13:13:06.928639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ba904fb211'
down_revision: Union[str, Sequence[str], None] = '3c2394a5856e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_license_type'), 'licenses', type_='unique')
    op.drop_constraint(op.f('licenses_user_id_fkey'), 'licenses', type_='foreignkey')
    op.drop_column('licenses', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('licenses_user_id_fkey'), 'licenses', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_user_license_type'), 'licenses', ['user_id', 'license_type_code'], postgresql_nulls_not_distinct=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    # ### end Alembic commands ###
